import PDFDocument from "pdfkit";
import { IProject } from "../models/Project";
import { ILandRecord } from "../models/LandRecord";

export class PdfReportService {
  public static generateProjectReport(project: IProject, parcels: ILandRecord[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Header
      doc.fillColor("#1e3a8a").fontSize(20).text("GOVERNMENT OF INDIA - LANDGUARD AI", { align: "center" });
      doc.fontSize(14).text("PREDICTIVE LAND ACQUISITION & RISK REPORT", { align: "center" });
      doc.moveDown(1);

      // Project Overview Section
      doc.fillColor("#000000").fontSize(12).text(`Project ID: ${project.id}`, { underline: true });
      doc.text(`Project Name: ${project.name}`);
      doc.text(`State / District: ${project.state} / ${project.district}`);
      doc.text(`Project Type: ${project.type}`);
      doc.text(`Required Area: ${project.landRequired} Hectares | Acquired: ${project.landAcquired} Hectares`);
      doc.text(`Acquisition Progress: ${project.progress}%`);
      doc.text(`Overall Delay Risk: ${project.delayRisk} | Predicted Delay: ${project.predictedDelay} Days`);
      doc.text(`Cost Overrun Estimate: ${project.costOverrun} Crores`);
      doc.moveDown(1);

      // Parcels Table Breakdown
      doc.fillColor("#1e3a8a").fontSize(14).text("Land Parcels Breakdown", { underline: true });
      doc.moveDown(0.5);

      doc.fillColor("#000000").fontSize(10);
      parcels.forEach((p, idx) => {
        doc.text(
          `${idx + 1}. Survey #${p.surveyNumber || p.id} | Owner: ${p.ownerName || 'N/A'} | Area: ${p.landArea} Acres | Risk: ${p.riskLevel || 'Low'} (${p.delayProbability || 20}%)`
        );
      });

      doc.moveDown(2);
      doc.fontSize(8).fillColor("#666666").text(`Report Generated by LandGuard AI System on ${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
    });
  }

  public static generateLandParcelReport(parcel: any, project?: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      const landId = parcel.id || "LA001";
      const surveyNo = parcel.surveyNumber || "124/2";
      const district = parcel.district || "Chennai";
      const state = parcel.state || "Tamil Nadu";
      const locName = parcel.location ? (parcel.location.split(",")[0] || parcel.location) : "Perungudi";
      const prjId = parcel.projectId || "TN-PRJ-001";
      const prjName = project?.name || `${prjId} Infrastructure Project`;
      const prjPurpose = project?.purpose || `${parcel.landType || parcel.landUse || 'Highway Development'} Acquisition`;
      const landAreaStr = `${parcel.landArea || parcel.area || 1.8} ${parcel.areaUnit || 'Hectare'}`;
      const latStr = parcel.latitude ? `${Number(parcel.latitude).toFixed(4)}° N` : "12.9650° N";
      const lngStr = parcel.longitude ? `${Number(parcel.longitude).toFixed(4)}° E` : "80.2460° E";
      const distStr = parcel.distanceFromProject ? `${parcel.distanceFromProject}` : "4.8";

      const documentStatus = parcel.documentStatus || (parcel.documentsComplete ? "Verified" : "Minor Discrepancy");
      const legalDispute = (parcel.courtCase || parcel.legalDispute) ? "Yes" : "No";
      const courtCaseCount = parcel.courtCaseCount !== undefined ? parcel.courtCaseCount : (parcel.courtCase ? 1 : 0);
      const compensationStatus = parcel.compensationStatus || "PARTIALLY_PAID";
      const rrStatus = parcel.rAndRStatus || parcel.rrStatus || "IN_PROGRESS";
      const approvalStatus = parcel.approvalStatus || (parcel.environmentalClearance ? "APPROVED" : "PENDING");

      const compAmount = parcel.compensationAmount || 0;
      const amtPaid = parcel.amountPaid || 0;
      const amtPending = parcel.amountPending !== undefined ? parcel.amountPending : (compAmount - amtPaid);
      const affectedFamilies = parcel.affectedFamilies !== undefined ? parcel.affectedFamilies : (parcel.ownersCount || 3);

      const plannedDays = parcel.plannedDays || 60;
      const actualDays = parcel.actualDays || 93;
      const delayDays = parcel.predictedDelayDays || parcel.delayDays || 33;
      const delayProbability = parcel.delayProbability || parcel.riskScore || 82;
      const riskLevel = String(parcel.riskLevel || "HIGH").toUpperCase();

      const todayDate = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
      const refCode = `LG-${landId}-${new Date().getFullYear()}${String(new Date().getMonth()+1).padStart(2,'0')}${String(new Date().getDate()).padStart(2,'0')}`;

      // --- HEADER & TITLE ---
      doc.fillColor("#0F172A").fontSize(13).font("Helvetica-Bold").text("LANDGUARD – LAND ACQUISITION RISK MONITORING SYSTEM", { align: "center" });
      doc.moveDown(0.3);
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#475569").text(`Date: ${todayDate}`, { align: "right" });
      doc.moveDown(0.5);

      // --- RECIPIENT ---
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#0F172A").text("To");
      doc.font("Helvetica").text("The Competent Authority / Concerned Land Acquisition Officer");
      doc.text(`[${prjName} Department]`);
      doc.text(`Government of ${state}`);
      doc.moveDown(0.8);

      // --- SUBJECT ---
      doc.font("Helvetica-Bold").fillColor("#0F172A").text(
        `Subject: Land Acquisition Status and Risk Assessment – Survey No. ${surveyNo}, ${locName}, ${district} – Reg.`
      );
      doc.moveDown(0.8);

      // --- SALUTATION & OPENING ---
      doc.font("Helvetica-Bold").text("Respected Sir/Madam,");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).fillColor("#1E293B").text(
        `This is to bring to your kind attention the status and preliminary risk assessment of the land parcel identified as Land ID: ${landId}, located at Survey No. ${surveyNo}, ${locName}, ${district}, ${state}, associated with the ${prjName} project.`,
        { lineGap: 2 }
      );
      doc.moveDown(0.5);
      doc.text(
        `The land parcel has been identified for ${prjPurpose} and has an approximate area of ${landAreaStr}. The location is recorded at approximately ${latStr}, ${lngStr}, with a distance of ${distStr} km from the project centre.`,
        { lineGap: 2 }
      );
      doc.moveDown(0.8);

      // --- SECTION 1: LAND PARTICULARS TABLE ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("1. Land Particulars");
      doc.moveDown(0.4);

      const table1Rows = [
        ["Land ID", landId],
        ["Project ID", prjId],
        ["Project Name", prjName],
        ["Project Purpose", prjPurpose],
        ["Survey Number", surveyNo],
        ["State", state],
        ["District", district],
        ["Location", locName],
        ["Land Area", landAreaStr],
        ["Land Use", parcel.landType || parcel.landUse || "Industrial"],
        ["Ownership Status", parcel.ownershipStatus || "Joint Ownership"],
        ["Owner Count", `${parcel.ownersCount || parcel.ownerCount || 1}`]
      ];

      let yPos = doc.y;
      const rowHeight = 16;
      doc.fontSize(8.5);

      // Header Row Table 1
      doc.rect(40, yPos, 515, rowHeight).fillAndStroke("#E2E8F0", "#94A3B8");
      doc.fillColor("#0F172A").font("Helvetica-Bold").text("Particular", 48, yPos + 4);
      doc.text("Details", 240, yPos + 4);
      yPos += rowHeight;

      // Data Rows Table 1
      table1Rows.forEach((r, idx) => {
        const bg = idx % 2 === 0 ? "#FFFFFF" : "#F8FAFC";
        doc.rect(40, yPos, 515, rowHeight).fillAndStroke(bg, "#CBD5E1");
        doc.fillColor("#334155").font("Helvetica-Bold").text(r[0], 48, yPos + 4);
        doc.fillColor("#0F172A").font("Helvetica").text(String(r[1]), 240, yPos + 4);
        yPos += rowHeight;
      });

      doc.y = yPos + 10;
      doc.moveDown(0.5);

      // --- SECTION 2: ACQUISITION & LEGAL STATUS ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("2. Acquisition & Legal Status");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).fillColor("#1E293B").text(
        `The available project data indicates that the land parcel is currently at the ${parcel.acquisitionStage || 'LEGAL_VERIFICATION'} stage of acquisition.`
      );
      doc.moveDown(0.4);

      doc.font("Helvetica").fontSize(9);
      const bulletList = [
        `• Document Status: ${documentStatus}`,
        `• Legal Dispute: ${legalDispute}`,
        `• Court Case Count: ${courtCaseCount}`,
        `• Compensation Status: ${compensationStatus}`,
        `• R&R Status: ${rrStatus}`,
        `• Approval Status: ${approvalStatus}`
      ];
      bulletList.forEach(bullet => {
        doc.text(bullet);
      });
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).text(
        "Where applicable, these matters may require verification and appropriate action by the concerned authority before the acquisition process proceeds to the next stage."
      );
      doc.moveDown(0.8);

      // Check if page overflow occurs, PDFKit creates page 2 automatically if needed
      // --- SECTION 3: COMPENSATION DETAILS TABLE ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("3. Compensation Details");
      doc.moveDown(0.4);

      const table3Rows = [
        ["Compensation Amount", `INR ₹ ${compAmount.toLocaleString('en-IN')}`],
        ["Amount Paid", `INR ₹ ${amtPaid.toLocaleString('en-IN')}`],
        ["Amount Pending", `INR ₹ ${amtPending.toLocaleString('en-IN')}`],
        ["Affected Families", `${affectedFamilies}`]
      ];

      yPos = doc.y;
      doc.fontSize(8.5);

      // Header Row Table 3
      doc.rect(40, yPos, 515, rowHeight).fillAndStroke("#E2E8F0", "#94A3B8");
      doc.fillColor("#0F172A").font("Helvetica-Bold").text("Particular", 48, yPos + 4);
      doc.text("Details", 360, yPos + 4, { align: "right", width: 180 });
      yPos += rowHeight;

      table3Rows.forEach((r, idx) => {
        const bg = idx % 2 === 0 ? "#FFFFFF" : "#F8FAFC";
        doc.rect(40, yPos, 515, rowHeight).fillAndStroke(bg, "#CBD5E1");
        doc.fillColor("#334155").font("Helvetica-Bold").text(r[0], 48, yPos + 4);
        doc.fillColor("#0F172A").font("Helvetica").text(r[1], 360, yPos + 4, { align: "right", width: 180 });
        yPos += rowHeight;
      });

      doc.y = yPos + 10;
      doc.moveDown(0.5);

      // --- SECTION 4: ACQUISITION PROGRESS ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("4. Acquisition Progress");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).fillColor("#1E293B").text(
        `The planned acquisition period for the selected land parcel is ${plannedDays} days, while the recorded/estimated actual period is ${actualDays} days.`
      );
      doc.moveDown(0.3);
      doc.font("Helvetica-Bold").fillColor("#B91C1C").text(`Current Delay: ${delayDays} days`);
      doc.moveDown(0.3);
      doc.font("Helvetica").fillColor("#1E293B").text(
        `The system has estimated a Delay Probability of ${delayProbability}% and classified the parcel under ${riskLevel} RISK.`
      );
      doc.moveDown(0.8);

      // --- SECTION 5: PRELIMINARY RISK ASSESSMENT ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("5. Preliminary Risk Assessment");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).text("The major factors contributing to the identified risk are:");
      doc.moveDown(0.3);
      
      const factor1 = legalDispute === "Yes" ? "Active court stay order / legal dispute" : (parcel.primaryDelayFactor || "Legal / title verification requirements");
      const factor2 = compensationStatus !== "PAID" && compensationStatus !== "Paid" ? "Pending compensation disbursement activities" : "Financial assessment and valuation clearance";
      const factor3 = documentStatus !== "Verified" ? "Document verification & patta discrepancy review" : "Section-15 landowner objection review";

      doc.text(`1. ${factor1}`);
      doc.text(`2. ${factor2}`);
      doc.text(`3. ${factor3}`);
      doc.moveDown(0.4);
      doc.text(
        "Based on the available data, the selected land parcel may require priority administrative attention and verification to minimise the possibility of further delay in the acquisition process."
      );
      doc.moveDown(0.8);

      // --- SECTION 6: RECOMMENDED ACTION ---
      doc.font("Helvetica-Bold").fontSize(10).fillColor("#0F172A").text("6. Recommended Action");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(9.5).text("It is recommended that the concerned authority may consider:");
      doc.moveDown(0.3);
      doc.text("1. Verification of ownership and relevant land records.");
      doc.text("2. Review and resolution of identified legal/document discrepancies.");
      doc.text("3. Review of pending compensation and rehabilitation matters.");
      doc.text("4. Reassessment of the acquisition risk after completion of the above actions.");
      doc.moveDown(0.8);

      // --- CLOSING & DISCLAIMER ---
      doc.font("Helvetica-Oblique").fontSize(8.5).fillColor("#475569").text(
        "The above assessment is generated by the LandGuard AI-based decision-support system using the available project and land-acquisition data. It is intended for preliminary monitoring and decision support and does not replace official records, statutory procedures, field verification, legal proceedings, or decisions of the competent authority.",
        { lineGap: 2 }
      );
      doc.moveDown(0.5);
      doc.font("Helvetica").fontSize(9.5).fillColor("#0F172A").text("Kindly consider the above information for appropriate review and further necessary action.");
      doc.moveDown(0.8);

      // --- SIGNOFF ---
      doc.font("Helvetica-Bold").fontSize(9.5).text("Yours faithfully,");
      doc.moveDown(0.3);
      doc.font("Helvetica-Bold").fillColor("#0F172A").text("LandGuard – AI-Based Land Acquisition Risk Monitoring System");
      doc.font("Helvetica").fillColor("#475569").text("Project Monitoring & Risk Assessment Module");
      doc.moveDown(0.6);
      doc.font("Helvetica-Bold").fillColor("#0F172A").text(`Report Reference: ${refCode}`);
      doc.font("Helvetica").text(`Enclosure: Land Acquisition Risk Assessment Report – ${landId}`);

      doc.end();
    });
  }

  public static generateAuditPdf(reportData: {
    title: string;
    date?: string;
    meta?: Record<string, any>;
    metrics?: Array<{ label: string; value: string }>;
    bodyText?: string;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Government Header
      doc.fillColor("#1e3a8a").fontSize(18).text("REVENUE DEPARTMENT - GOVERNMENT OF TAMIL NADU", { align: "center" });
      doc.fontSize(12).fillColor("#475569").text("SPECIAL LAND ACQUISITION (SLA) OFFICIAL AUDIT DOSSIER", { align: "center" });
      doc.moveDown(1);

      // Title & Date
      doc.fillColor("#0f172a").fontSize(14).text(reportData.title.toUpperCase(), { underline: true });
      doc.fontSize(10).fillColor("#64748b").text(`Date of Generation: ${reportData.date || new Date().toLocaleDateString()}`);
      doc.text(`Digital Seal: SHA256-AUTHENTICATED-${Date.now().toString(16).toUpperCase()}`);
      doc.moveDown(1);

      // Metadata Box
      if (reportData.meta && Object.keys(reportData.meta).length > 0) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Metadata Overview", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(10);
        Object.entries(reportData.meta).forEach(([k, v]) => {
          doc.text(`• ${k}: ${v}`);
        });
        doc.moveDown(1);
      }

      // Compiled Figures & Metrics
      if (reportData.metrics && reportData.metrics.length > 0) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Compiled Audit Figures & Statutory Metrics", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(10);
        reportData.metrics.forEach((m) => {
          doc.text(`• ${m.label}: ${m.value}`);
        });
        doc.moveDown(1);
      }

      // Optional Body Text (for inquiry letters or custom text)
      if (reportData.bodyText) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Official Statement & Contents", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(9).text(reportData.bodyText, { lineGap: 3 });
        doc.moveDown(1);
      }

      // Footer notice
      doc.moveDown(2);
      doc.fontSize(8).fillColor("#475569").text(
        "Statutory Notice: Document compiled under Section 15 of RFCTLARR Act 2013. Digitally authorized by LandGuard AI Special Revenue Officer.",
        { align: "center" }
      );

      doc.end();
    });
  }
}
